name: FRIENDS of Sullivan's Island Elementary School
shortName: FRIENDS of SIES
tagline: FRIENDS builds what's possible.
email: hello@siesfriends.org
advertisingEmail: hello@siesfriends.org
donateUrl: https://coastal.fcsuite.com/erp/donate/create/fund?funit_id=1900
taxLine: Donations are tax-deductible through the Coastal Community Foundation, a 501⁠(c)⁠(3) public charity.
