name: FRIENDS of Sullivan's Island Elementary School
shortName: FRIENDS of SIES
tagline: Friends builds what's possible.
email: siesfriends.skimmers@gmail.com
advertisingEmail: siesfriends.skimmers@gmail.com
taxLine: Donations are tax-deductible through the Coastal Community Foundation, a 501⁠(c)⁠(3) public charity.
